export default {
  primary: '#4C6EE1',
  white: '#FFFFFF',
  success: '#56B05A',
  warningYellow: '#FFB938',
  danger: '#EE4E38',
  darkGray: '#BAC1D7',
  lightGray: '#BEC2CC',
  black: '#000000',
  warningOrange: '#EE8438',
  backgroundDefault: '#373941',
  buttonDisabled: '#8EA6F8',
  iconsPrimary: '#BAC1D7',
  textBasic: '#EEEFF3',
  textHint: '#BEC2CC',
  textDisabled: '#BAC1D7',
  inputLabel: '#BEC2CC',
  inputBackgroundDisabled: '#63666e',
  inputBorder: '#BEC2CC',
  contentBackgroundGrey: '#363841',
  cardBackground: '#464953',
  invertiblePrimary: '#FFFFFF', // Black for light theme, white for dark theme
  fullOpacity: 'rgba(0, 0, 0, 0)',
  opacityBehindMenu: 'rgba(0, 0, 0, 0.1)',
  borderPrimary: '#8EA6F8',
};
