export default {
  primary: '#4C6EE1',
  success: '#56B05A',
  warningYellow: '#FFB938',
  danger: '#EE4E38',
  white: '#FFFFFF',
  darkGray: '#6B7077',
  lightGray: '#BEC2CC',
  black: '#000000',
  warningOrange: '#EE8438',
  backgroundDefault: '#EEEFF3',
  buttonDisabled: '#8EA6F8',
  iconsPrimary: '#BAC1D7',
  textBasic: '#464953',
  textHint: '#7B7F87',
  textDisabled: '#FFFFFF',
  inputLabel: '#7B7F87',
  inputBackgroundDisabled: '#EEEFF3',
  inputBorder: '#BEC2CC',
  contentBackgroundGrey: '#EEEFF3',
  cardBackground: '#FFFFFF',
  invertiblePrimary: '#000000', // Black for light theme, white for dark theme
  fullOpacity: 'rgba(0, 0, 0, 0)',
  opacityBehindMenu: 'rgba(0, 0, 0, 0.1)',
  borderPrimary: '#5973CC',

};
